#!/usr/bin/env node

var path = require('path');
var rootDir = process.cwd();
var projDir = path.join(rootDir, 'WebApp');
var tuanCsproj = path.join(projDir, 'Tuan.csproj');
var mode = process.argv[2];
if (/release|r/i.test(mode)) {
    mode = 'Release';
} else {
    mode = 'Debug';
}
/**
 * 使用msbuild编译，需在Windows环境变量加入如下路径：
 * C:\Windows\Microsoft.NET\Framework\v4.0.30319
 */
var command = 'msbuild /v:q /t:Rebuild /p:Configuration=' + mode + ';IntermediateOutputPath=' + projDir + '\\ ' + tuanCsproj;
require('child_process').exec(command, function (err) {
    if (err) {
        console.log(err);
    } else {
        console.log(mode + ' mode build success')
    }
});
