#!/usr/bin/env node

var path = require('path');
var exec = require('child_process').exec;

var rootDir = process.cwd();
var projDir = path.join(rootDir, 'WebApp');
var tuanCsproj = path.join(projDir, 'Tuan.csproj');
var mode = process.argv[2];
if (/release|r/i.test(mode)) {
    mode = 'Release';
} else {
    mode = 'Debug';
}

exec('msbuild /v:q /t:Rebuild /p:Configuration=' + mode + ';IntermediateOutputPath=' + projDir + '\\ ' + tuanCsproj);
